#KMOD= syscall
#SRCS= syscall.c

#KMOD = hook
#SRCS= hook.c

#KMOD= interface
#SRCS= interface.c

#KMOD = process_hiding2
#SRCS= process_hiding2.c

#KMOD = port_hiding
#SRCS = port_hiding.c

#KMOD = incog3
#SRCS = incog3.c

#KMOD = trojan_loader
#SRCS = trojan_loader.c

KMOD = assignHid
SRCS = assignHid.c

.include <bsd.kmod.mk>
