KMOD= syscall
SRCS= syscall.c

KMOD = hook
SRCS= hook.c

#KMOD= interface
#SRCS= interface.c

KMOD = process_hiding2
SRCS= process_hiding2.c

KMOD = port_hiding
SRCS = port_hiding.c

.include <bsd.kmod.mk>
